name: Terraform Gateway Destroy on AWS

on:
  workflow_dispatch:

jobs:
  # Job para destruir os recursos do gateway no AWS com Terraform
  destroy:
    name: Terraform Destroy Gateway
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      # Inicializar e validar o Terraform
      - name: Initialize Terraform for Gateway
        working-directory: terraform
        run: terraform init

      - name: Validate Terraform for Gateway
        working-directory: terraform
        run: terraform validate

      # Executar o Terraform Destroy
      - name: Destroy Terraform for Gateway
        working-directory: terraform
        run: terraform destroy -auto-approve
